name: fnp_gifts
description: A gift and flowers shopping app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cached_network_image: ^3.3.1
  smooth_page_indicator: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.18.1
  cached_network_image_web: ^1.1.1
  cached_network_image_platform_interface: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true